// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// is_integer
LogicalVector is_integer(CharacterVector v);
RcppExport SEXP pformat_is_integer(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(is_integer(v));
    return rcpp_result_gen;
END_RCPP
}
// markup
List markup();
RcppExport SEXP pformat_markup() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(markup());
    return rcpp_result_gen;
END_RCPP
}
// pformat_parse2
List pformat_parse2(StringVector str);
RcppExport SEXP pformat_pformat_parse2(SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(pformat_parse2(str));
    return rcpp_result_gen;
END_RCPP
}
