# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Tells if a string represents an integer
#' 
#' Checks if the characters in a string are in the interval '0' .. '9'
#' 
#' @param v a string vector
#' 
#' @return a logical vector 
#' @export
is_integer <- function(v) {
    .Call('pformat_is_integer', PACKAGE = 'pformat', v)
}

#' Preparses a format string
#'
#' @description  Parses a format string into an internal representation
#' compatible with \code{pformat()}.
#'
#' @param format_string the format string
#'
#' @return an object of class \code{pformat.compiled} containing an internal
#' representation of the format string.
#' @export
#'
#' @details This function actually only parses a "layer" of the format string
#' markup. Recursive format strings depend on data, and thus can't be
#' completely parsed yet. In these cases, \code{pformat_parse()} will still be
#' called by \code{pformat()} with format specifications needing expanding.
#'
#' @examples
#' pformat_parse("{} {}")
#' pformat_parse("{1} {2}")
#' @export
pformat_parse <- function(format_string) {
    .Call('pformat_pformat_parse', PACKAGE = 'pformat', format_string)
}

