# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Tells if a string represents an integer
#' 
#' Checks if the characters in a string are in the interval '0' .. '9'
#' 
#' @param v a string vector
#' 
#' @return a logical vector 
#' @export
is_integer <- function(v) {
    .Call('pformat_is_integer', PACKAGE = 'pformat', v)
}

